export const teamOfExperts = ref([
    {
        id: 'b241-1af2a-4gab-01',
        name: 'Trần Quốc Lợi',
        gender: 'Male',
        duty: 'Cổ đông sáng lập',
        img: 'https://static1.cbrimages.com/wordpress/wp-content/uploads/2021/06/TheRock.jpg',
        experience: [
            'Đồng sáng lập iCheck',
            'Đồng sáng lập HecaTech',
            'Kinh nghiệm làm việc tại các vị trí cấp cao tại VNPT và VMG',
            '15 năm đầu tư trong lĩnh vực công nghệ thông tin',
            '6 năm đầu tư trong lĩnh vực thương mại điện tử',
            'Từng gọi vốn thành công với nhiều Start-Up',
            'Kinh nghiệm trong xây dựng chiến lược, quản lý tổ chức và',
            'vận hành bộ máy theo quy mô tập đoàn',
        ],
        phone: '+84 347 000 678',
        email: 'tranquocloi@gmail.com',
    },
    {
        id: 'c312-2bd4c-9hdf-02',
        name: 'Nguyễn Mai Linh',
        gender: 'Female',
        duty: 'Giám đốc chiến lược',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Elizabeth_Olsen_at_the_2024_Toronto_International_Film_Festival_2_%28better_crop%29.jpg/1200px-Elizabeth_Olsen_at_the_2024_Toronto_International_Film_Festival_2_%28better_crop%29.jpg',
        experience: [
            '10 năm kinh nghiệm tại các tập đoàn đa quốc gia trong lĩnh vực FMCG',
            '5 năm tư vấn chiến lược cho các Start-Up công nghệ',
            'Từng là quản lý cấp cao tại Deloitte Việt Nam',
            'Chuyên gia phân tích thị trường và hành vi tiêu dùng',
            'Kinh nghiệm triển khai chiến lược Go-To-Market',
        ],
        phone: '+84 912 345 678',
        email: 'maimarketing@gmail.com',
    },
    {
        id: 'd124-7eg9z-2nmc-03',
        name: 'Phạm Văn Hùng',
        gender: 'Male',
        duty: 'Chuyên gia công nghệ',
        img: 'https://cdn.galaxycine.vn/media/h/u/hu-doc.jpg',
        experience: [
            'CTO tại một công ty công nghệ lọt top 10 Startup tại Việt Nam',
            '15 năm kinh nghiệm phát triển hệ thống phần mềm quy mô lớn',
            'Từng làm việc tại FPT Software và Samsung R&D',
            'Chuyên về kiến trúc hệ thống, DevOps, và AI ứng dụng',
        ],
        phone: '+84 988 888 888',
        email: 'hungtech@gmail.com',
    },
    {
        id: 'e563-3lk9p-8bbc-04',
        name: 'Lê Minh Tuấn',
        gender: 'Male',
        duty: 'Cố vấn tài chính',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Chris_Hemsworth_by_Gage_Skidmore_2_%28cropped%29.jpg/1200px-Chris_Hemsworth_by_Gage_Skidmore_2_%28cropped%29.jpg',
        experience: [
            'Tốt nghiệp MBA chuyên ngành Tài chính tại Anh Quốc',
            '8 năm làm việc tại Ernst & Young',
            'Chuyên gia gọi vốn và định giá doanh nghiệp khởi nghiệp',
            'Cố vấn tài chính cho hơn 20 dự án Startup tại Đông Nam Á',
        ],
        phone: '+84 901 111 222',
        email: 'tuanfinance@gmail.com',
    },
    {
        id: 'f982-4jkd2-7pqa-05',
        name: 'Vũ Thị Kim Ngân',
        gender: 'Female',
        duty: 'Chuyên gia vận hành',
        img: 'https://kenh14cdn.com/203336854389633024/2024/2/8/photo-1-1707387442155399580321.jpg',
        experience: [
            '12 năm quản lý vận hành chuỗi cung ứng tại Unilever Việt Nam',
            'Tư vấn hệ thống quản trị vận hành cho doanh nghiệp SME',
            'Kinh nghiệm xây dựng KPI và quy trình vận hành nội bộ',
            'Từng triển khai ERP và các hệ thống quản lý cho nhiều doanh nghiệp',
        ],
        phone: '+84 923 456 789',
        email: 'nganops@gmail.com',
    },
    {
        id: 'g207-8mprx-5lsa-06',
        name: 'Đặng Hoàng Nam',
        gender: 'Male',
        duty: 'Cố vấn khởi nghiệp',
        img: 'https://m.media-amazon.com/images/M/MV5BNzQ0YWM1ODEtZDFkYy00MGJhLTkwZDUtMzVkZjljODU3ZTRmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
        experience: [
            'Thành viên hội đồng cố vấn nhiều chương trình ươm tạo Startup',
            'Kinh nghiệm khởi nghiệp với 3 công ty công nghệ tại Việt Nam và Singapore',
            'Từng đạt giải thưởng Startup sáng tạo khu vực ASEAN',
            'Diễn giả tại các sự kiện khởi nghiệp và đổi mới sáng tạo',
        ],
        phone: '+84 965 789 123',
        email: 'namstartup@gmail.com',
    }
])